services:
  influxdb:
    image: influxdb:2.7
    container_name: influxdb
    ports:
      - "8086:8086"
    volumes:
      - influxdb-data:/var/lib/influxdb2
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=admin
      - DOCKER_INFLUXDB_INIT_PASSWORD=thu.1234
      - DOCKER_INFLUXDB_INIT_ORG=thu-de
      - DOCKER_INFLUXDB_INIT_BUCKET=SmartPacifier-Bucket1
      - DOCKER_INFLUXDB_INIT_RETENTION=365d  
    restart: unless-stopped

  mosquitto:
    image: eclipse-mosquitto:2.0
    container_name: mosquitto
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - mosquitto-data:/mosquitto/data
      - mosquitto-log:/mosquitto/log
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf
    restart: unless-stopped
    environment:
      - MQTT_ALLOW_ANONYMOUS=true

  python_service:
    image: python:3.8
    container_name: python_service
    command: sh -c "mkdir -p /scripts && tail -f /dev/null"  # Creates /scripts directory and keeps container running
    restart: unless-stopped


volumes:
  influxdb-data:
  mosquitto-data:
  mosquitto-log:
