version: '3'
services:
  mosquitto:
    image: eclipse-mosquitto:2.0.20

  influxdb:
    image: influxdb:2.7
    container_name: influxdb
    ports:
      - "8086:8086"
    volumes:
      - influxdb-data:/var/lib/influxdb2  # Persisting the data locally
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=admin  # You set this value
      - DOCKER_INFLUXDB_INIT_PASSWORD=thu.1234  # You set this value
      - DOCKER_INFLUXDB_INIT_ORG=thu-de  # You set this value
      - DOCKER_INFLUXDB_INIT_BUCKET=my-bucket  # You set this value
volumes:
  influxdb-data:
