name: .NET Core Desktop

on:
  push:
    branches: [ "main-Production-Environment" ]
  pull_request:
    branches: [ "main-Production-Environment" ]

jobs:
  build:
    strategy:
      matrix:
        configuration: [Debug, Release]

    runs-on: windows-latest

    env:
      Solution_Name: "TeamOrientedProject---Smart-Pacifier/Testing_Integration_Environment/SmartPacifier - TestingFramework/SmartPacifier - TestingFramework.sln"  # Full path to the solution file
      Test_Project_Path: "TeamOrientedProject---Smart-Pacifier/Testing_Integration_Environment/SmartPacifier - TestingFramework/SmartPacifier - TestingFramework/SmartPacifier - TestingFramework.csproj"  # Full path to the test project file

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Install .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v2

    # Run dotnet test for the entire solution to confirm setup
    - name: Execute all tests in the solution
      run: dotnet test "${{ env.Solution_Name }}" --configuration ${{ matrix.configuration }} --no-build --verbosity normal

    # Execute unit tests in Main_UnitTests class
    - name: Execute unit tests in Main_UnitTests class
      run: dotnet test "${{ env.Test_Project_Path }}" --configuration ${{ matrix.configuration }} --no-build --verbosity normal --filter "FullyQualifiedName~SmartPacifier___TestingFramework.Main_UnitTests"

    - name: Restore the application
      run: msbuild "${{ env.Solution_Name }}" /t:Restore /p:Configuration=$env:Configuration
      env:
        Configuration: ${{ matrix.configuration }}
